#ifndef UI_CONSTANTS_H
#define UI_CONSTANTS_H

// Window dimensions
#define WINDOW_WIDTH_UI 1120
#define WINDOW_HEIGHT_UI 720

// Notification system
#define NOTIFICATION_DURATION_MS 3000
#define NOTIFICATION_FADE_START_MS 2500

// UI Layout - Login/Register Screen
#define LOGIN_INPUT_X 335
#define LOGIN_INPUT_Y_USERNAME 240
#define LOGIN_INPUT_Y_EMAIL 340
#define LOGIN_INPUT_Y_PASSWORD 440
#define LOGIN_INPUT_WIDTH 450
#define LOGIN_INPUT_HEIGHT 65

#define LOGIN_BUTTON_Y 560
#define LOGIN_BUTTON_WIDTH 180
#define LOGIN_BUTTON_HEIGHT 60
#define LOGIN_BUTTON_X_LEFT 335
#define LOGIN_BUTTON_X_RIGHT 605

// UI Layout - Lobby List Screen  
#define LOBBY_BUTTON_Y 620
#define LOBBY_BUTTON_HEIGHT 60
#define LOBBY_BUTTON_WIDTH 200
#define LOBBY_BUTTON_SPACING 10

// Lobby buttons X positions (for 1120 width)
#define LOBBY_BTN_CREATE_X 250
#define LOBBY_BTN_REFRESH_X 460
#define LOBBY_BTN_FRIENDS_X 670
#define LOBBY_BTN_QUICKPLAY_X 880

// Top bar buttons
#define TOP_BTN_PROFILE_X 850
#define TOP_BTN_PROFILE_Y 20
#define TOP_BTN_PROFILE_WIDTH 130
#define TOP_BTN_PROFILE_HEIGHT 50

#define TOP_BTN_LEADERBOARD_X 1000
#define TOP_BTN_LEADERBOARD_Y 20
#define TOP_BTN_LEADERBOARD_WIDTH 80
#define TOP_BTN_LEADERBOARD_HEIGHT 50

// Lobby Room Screen
#define ROOM_BUTTON_Y 630
#define ROOM_BUTTON_WIDTH 200
#define ROOM_BUTTON_HEIGHT 50
#define ROOM_BUTTON_X_READY 80
#define ROOM_BUTTON_X_LEAVE 320

// Room creation dialog
#define ROOM_CREATE_INPUT_X 335
#define ROOM_CREATE_NAME_Y 260
#define ROOM_CREATE_CODE_Y 350
#define ROOM_CREATE_INPUT_WIDTH 450
#define ROOM_CREATE_INPUT_HEIGHT 60

#define ROOM_CREATE_BTN_Y 440
#define ROOM_CREATE_BTN_WIDTH 220
#define ROOM_CREATE_BTN_HEIGHT 60
#define ROOM_CREATE_BTN_X_CONFIRM 370
#define ROOM_CREATE_BTN_X_CANCEL 620

// Settings screen
#define SETTINGS_BTN_X 40
#define SETTINGS_BTN_Y 620
#define SETTINGS_BTN_WIDTH 200
#define SETTINGS_BTN_HEIGHT 60

// Post-match screen
#define POST_MATCH_BTN_Y 800
#define POST_MATCH_BTN_WIDTH 250
#define POST_MATCH_BTN_HEIGHT 60
#define POST_MATCH_BTN_X_REMATCH 360
#define POST_MATCH_BTN_X_RETURN 610

// Logout button
#define LOGOUT_BTN_X 40
#define LOGOUT_BTN_Y 45
#define LOGOUT_BTN_WIDTH 120
#define LOGOUT_BTN_HEIGHT 50

// Friend system
#define FRIEND_INPUT_X 400
#define FRIEND_INPUT_Y 620
#define FRIEND_INPUT_WIDTH 360
#define FRIEND_INPUT_HEIGHT 60

#define FRIEND_BTN_SEND_X 800
#define FRIEND_BTN_SEND_Y 620
#define FRIEND_BTN_SEND_WIDTH 220
#define FRIEND_BTN_SEND_HEIGHT 60

// Join code dialog
#define JOIN_CODE_INPUT_X 335
#define JOIN_CODE_INPUT_Y 320
#define JOIN_CODE_INPUT_WIDTH 450
#define JOIN_CODE_INPUT_HEIGHT 60

// Invite system
#define INVITE_BTN_OPEN_X 910
#define INVITE_BTN_OPEN_Y 15
#define INVITE_BTN_OPEN_WIDTH 180
#define INVITE_BTN_OPEN_HEIGHT 50

// Chat system
#define MAX_CHAT_MESSAGES 50
#define CHAT_INPUT_WIDTH 600
#define CHAT_INPUT_HEIGHT 40
#define CHAT_MESSAGE_MAX_LENGTH 199

#endif // UI_CONSTANTS_H
